deploy_to_webeos:
  image: rclone/rclone:latest
  script:
    - |
      rclone copy ./ :webdav: \
        --webdav-url="https://eosuser.cern.ch/eos/home-s/sdonato/ERNEST-website/ERNESTWeb" \
        --webdav-vendor="other" \
        --webdav-bearer-token="$EOS_TOKEN" \
        --exclude=".git/**" \
        --exclude=".github/**" \
        --exclude=".gitlab-ci.yml"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" # Change to "master" if necessary
