deploy_to_webeos:
  stage: deploy
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  variables:
    # La cartella locale del tuo repository da copiare ("." significa tutto il repo)
    CI_OUTPUT_DIR: "."
    
    # Il percorso di destinazione esatto su WebEOS
    EOS_PATH: "/eos/user/s/sdonato/ERNEST-website/ERNESTWeb"
  script:
    - deploy-eos
  rules:
    - if: $CI_COMMIT_BRANCH == "main" # Assicurati che sia il nome corretto del tuo branch principale
